package migration

import (
	"fmt"
	"log"
	"syncerland/core/initializers"
	"syncerland/models"

	"gorm.io/gorm"
)

func SeedCountries() {

	panicMessage := "Failed to seed country table!"

	var count int64
	if err := initializers.DB.Model(&models.Country{}).Count(&count).Error; err != nil {
		log.Fatal(err)
		panic(panicMessage)
	}

	// Create instances of the Country struct for each record
	countries := []models.Country{
		{Model: gorm.Model{ID: 1}, Alpha2: "af", Alpha3: "afg", Name: "Afghanistan"},
		{Model: gorm.Model{ID: 2}, Alpha2: "al", Alpha3: "alb", Name: "Albania"},
		{Model: gorm.Model{ID: 3}, Alpha2: "dz", Alpha3: "dza", Name: "Algeria"},
		{Model: gorm.Model{ID: 4}, Alpha2: "ad", Alpha3: "and", Name: "Andorra"},
		{Model: gorm.Model{ID: 5}, Alpha2: "ao", Alpha3: "ago", Name: "Angola"},
		{Model: gorm.Model{ID: 6}, Alpha2: "ag", Alpha3: "atg", Name: "Antigua and Barbuda"},
		{Model: gorm.Model{ID: 7}, Alpha2: "ar", Alpha3: "arg", Name: "Argentina"},
		{Model: gorm.Model{ID: 8}, Alpha2: "am", Alpha3: "arm", Name: "Armenia"},
		{Model: gorm.Model{ID: 9}, Alpha2: "au", Alpha3: "aus", Name: "Australia"},
		{Model: gorm.Model{ID: 10}, Alpha2: "at", Alpha3: "aut", Name: "Austria"},
		{Model: gorm.Model{ID: 11}, Alpha2: "az", Alpha3: "aze", Name: "Azerbaijan"},
		{Model: gorm.Model{ID: 12}, Alpha2: "bs", Alpha3: "bhs", Name: "Bahamas"},
		{Model: gorm.Model{ID: 13}, Alpha2: "bh", Alpha3: "bhr", Name: "Bahrain"},
		{Model: gorm.Model{ID: 14}, Alpha2: "bd", Alpha3: "bgd", Name: "Bangladesh"},
		{Model: gorm.Model{ID: 15}, Alpha2: "bb", Alpha3: "brb", Name: "Barbados"},
		{Model: gorm.Model{ID: 16}, Alpha2: "by", Alpha3: "blr", Name: "Belarus"},
		{Model: gorm.Model{ID: 17}, Alpha2: "be", Alpha3: "bel", Name: "Belgium"},
		{Model: gorm.Model{ID: 18}, Alpha2: "bz", Alpha3: "blz", Name: "Belize"},
		{Model: gorm.Model{ID: 19}, Alpha2: "bj", Alpha3: "ben", Name: "Benin"},
		{Model: gorm.Model{ID: 20}, Alpha2: "bt", Alpha3: "btn", Name: "Bhutan"},
		{Model: gorm.Model{ID: 21}, Alpha2: "bo", Alpha3: "bol", Name: "Bolivia (Plurinational State of)"},
		{Model: gorm.Model{ID: 22}, Alpha2: "ba", Alpha3: "bih", Name: "Bosnia and Herzegovina"},
		{Model: gorm.Model{ID: 23}, Alpha2: "bw", Alpha3: "bwa", Name: "Botswana"},
		{Model: gorm.Model{ID: 24}, Alpha2: "br", Alpha3: "bra", Name: "Brazil"},
		{Model: gorm.Model{ID: 25}, Alpha2: "bn", Alpha3: "brn", Name: "Brunei Darussalam"},
		{Model: gorm.Model{ID: 26}, Alpha2: "bg", Alpha3: "bgr", Name: "Bulgaria"},
		{Model: gorm.Model{ID: 27}, Alpha2: "bf", Alpha3: "bfa", Name: "Burkina Faso"},
		{Model: gorm.Model{ID: 28}, Alpha2: "bi", Alpha3: "bdi", Name: "Burundi"},
		{Model: gorm.Model{ID: 29}, Alpha2: "cv", Alpha3: "cpv", Name: "Cabo Verde"},
		{Model: gorm.Model{ID: 30}, Alpha2: "kh", Alpha3: "khm", Name: "Cambodia"},
		{Model: gorm.Model{ID: 31}, Alpha2: "cm", Alpha3: "cmr", Name: "Cameroon"},
		{Model: gorm.Model{ID: 32}, Alpha2: "ca", Alpha3: "can", Name: "Canada"},
		{Model: gorm.Model{ID: 33}, Alpha2: "cf", Alpha3: "caf", Name: "Central African Republic"},
		{Model: gorm.Model{ID: 34}, Alpha2: "td", Alpha3: "tcd", Name: "Chad"},
		{Model: gorm.Model{ID: 35}, Alpha2: "cl", Alpha3: "chl", Name: "Chile"},
		{Model: gorm.Model{ID: 36}, Alpha2: "cn", Alpha3: "chn", Name: "China"},
		{Model: gorm.Model{ID: 37}, Alpha2: "co", Alpha3: "col", Name: "Colombia"},
		{Model: gorm.Model{ID: 38}, Alpha2: "km", Alpha3: "com", Name: "Comoros"},
		{Model: gorm.Model{ID: 39}, Alpha2: "cg", Alpha3: "cog", Name: "Congo"},
		{Model: gorm.Model{ID: 40}, Alpha2: "cd", Alpha3: "cod", Name: "Congo, Democratic Republic of the"},
		{Model: gorm.Model{ID: 41}, Alpha2: "cr", Alpha3: "cri", Name: "Costa Rica"},
		{Model: gorm.Model{ID: 42}, Alpha2: "ci", Alpha3: "civ", Name: "CÃ´te d'Ivoire"},
		{Model: gorm.Model{ID: 43}, Alpha2: "hr", Alpha3: "hrv", Name: "Croatia"},
		{Model: gorm.Model{ID: 44}, Alpha2: "cu", Alpha3: "cub", Name: "Cuba"},
		{Model: gorm.Model{ID: 45}, Alpha2: "cy", Alpha3: "cyp", Name: "Cyprus"},
		{Model: gorm.Model{ID: 46}, Alpha2: "cz", Alpha3: "cze", Name: "Czechia"},
		{Model: gorm.Model{ID: 47}, Alpha2: "dk", Alpha3: "dnk", Name: "Denmark"},
		{Model: gorm.Model{ID: 48}, Alpha2: "dj", Alpha3: "dji", Name: "Djibouti"},
		{Model: gorm.Model{ID: 49}, Alpha2: "dm", Alpha3: "dma", Name: "Dominica"},
		{Model: gorm.Model{ID: 50}, Alpha2: "do", Alpha3: "dom", Name: "Dominican Republic"},
		{Model: gorm.Model{ID: 51}, Alpha2: "ec", Alpha3: "ecu", Name: "Ecuador"},
		{Model: gorm.Model{ID: 52}, Alpha2: "eg", Alpha3: "egy", Name: "Egypt"},
		{Model: gorm.Model{ID: 53}, Alpha2: "sv", Alpha3: "slv", Name: "El Salvador"},
		{Model: gorm.Model{ID: 54}, Alpha2: "gq", Alpha3: "gnq", Name: "Equatorial Guinea"},
		{Model: gorm.Model{ID: 55}, Alpha2: "er", Alpha3: "eri", Name: "Eritrea"},
		{Model: gorm.Model{ID: 56}, Alpha2: "ee", Alpha3: "est", Name: "Estonia"},
		{Model: gorm.Model{ID: 57}, Alpha2: "sz", Alpha3: "swz", Name: "Eswatini"},
		{Model: gorm.Model{ID: 58}, Alpha2: "et", Alpha3: "eth", Name: "Ethiopia"},
		{Model: gorm.Model{ID: 59}, Alpha2: "fj", Alpha3: "fji", Name: "Fiji"},
		{Model: gorm.Model{ID: 60}, Alpha2: "fi", Alpha3: "fin", Name: "Finland"},
		{Model: gorm.Model{ID: 61}, Alpha2: "fr", Alpha3: "fra", Name: "France"},
		{Model: gorm.Model{ID: 62}, Alpha2: "ga", Alpha3: "gab", Name: "Gabon"},
		{Model: gorm.Model{ID: 63}, Alpha2: "gm", Alpha3: "gmb", Name: "Gambia"},
		{Model: gorm.Model{ID: 64}, Alpha2: "ge", Alpha3: "geo", Name: "Georgia"},
		{Model: gorm.Model{ID: 65}, Alpha2: "de", Alpha3: "deu", Name: "Germany"},
		{Model: gorm.Model{ID: 66}, Alpha2: "gh", Alpha3: "gha", Name: "Ghana"},
		{Model: gorm.Model{ID: 67}, Alpha2: "gr", Alpha3: "grc", Name: "Greece"},
		{Model: gorm.Model{ID: 68}, Alpha2: "gd", Alpha3: "grd", Name: "Grenada"},
		{Model: gorm.Model{ID: 69}, Alpha2: "gt", Alpha3: "gtm", Name: "Guatemala"},
		{Model: gorm.Model{ID: 70}, Alpha2: "gn", Alpha3: "gin", Name: "Guinea"},
		{Model: gorm.Model{ID: 71}, Alpha2: "gw", Alpha3: "gnb", Name: "Guinea-Bissau"},
		{Model: gorm.Model{ID: 72}, Alpha2: "gy", Alpha3: "guy", Name: "Guyana"},
		{Model: gorm.Model{ID: 73}, Alpha2: "ht", Alpha3: "hti", Name: "Haiti"},
		{Model: gorm.Model{ID: 74}, Alpha2: "hn", Alpha3: "hnd", Name: "Honduras"},
		{Model: gorm.Model{ID: 75}, Alpha2: "hu", Alpha3: "hun", Name: "Hungary"},
		{Model: gorm.Model{ID: 76}, Alpha2: "is", Alpha3: "isl", Name: "Iceland"},
		{Model: gorm.Model{ID: 77}, Alpha2: "in", Alpha3: "ind", Name: "India"},
		{Model: gorm.Model{ID: 78}, Alpha2: "id", Alpha3: "idn", Name: "Indonesia"},
		{Model: gorm.Model{ID: 79}, Alpha2: "ir", Alpha3: "irn", Name: "Iran (Islamic Republic of)"},
		{Model: gorm.Model{ID: 80}, Alpha2: "iq", Alpha3: "irq", Name: "Iraq"},
		{Model: gorm.Model{ID: 81}, Alpha2: "ie", Alpha3: "irl", Name: "Ireland"},
		{Model: gorm.Model{ID: 82}, Alpha2: "il", Alpha3: "isr", Name: "Israel"},
		{Model: gorm.Model{ID: 83}, Alpha2: "it", Alpha3: "ita", Name: "Italy"},
		{Model: gorm.Model{ID: 84}, Alpha2: "jm", Alpha3: "jam", Name: "Jamaica"},
		{Model: gorm.Model{ID: 85}, Alpha2: "jp", Alpha3: "jpn", Name: "Japan"},
		{Model: gorm.Model{ID: 86}, Alpha2: "jo", Alpha3: "jor", Name: "Jordan"},
		{Model: gorm.Model{ID: 87}, Alpha2: "kz", Alpha3: "kaz", Name: "Kazakhstan"},
		{Model: gorm.Model{ID: 88}, Alpha2: "ke", Alpha3: "ken", Name: "Kenya"},
		{Model: gorm.Model{ID: 89}, Alpha2: "ki", Alpha3: "kir", Name: "Kiribati"},
		{Model: gorm.Model{ID: 90}, Alpha2: "kp", Alpha3: "prk", Name: "Korea (Democratic People's Republic of)"},
		{Model: gorm.Model{ID: 91}, Alpha2: "kr", Alpha3: "kor", Name: "Korea, Republic of"},
		{Model: gorm.Model{ID: 92}, Alpha2: "kw", Alpha3: "kwt", Name: "Kuwait"},
		{Model: gorm.Model{ID: 93}, Alpha2: "kg", Alpha3: "kgz", Name: "Kyrgyzstan"},
		{Model: gorm.Model{ID: 94}, Alpha2: "la", Alpha3: "lao", Name: "Lao People's Democratic Republic"},
		{Model: gorm.Model{ID: 95}, Alpha2: "lv", Alpha3: "lva", Name: "Latvia"},
		{Model: gorm.Model{ID: 96}, Alpha2: "lb", Alpha3: "lbn", Name: "Lebanon"},
		{Model: gorm.Model{ID: 97}, Alpha2: "ls", Alpha3: "lso", Name: "Lesotho"},
		{Model: gorm.Model{ID: 98}, Alpha2: "lr", Alpha3: "lbr", Name: "Liberia"},
		{Model: gorm.Model{ID: 99}, Alpha2: "ly", Alpha3: "lby", Name: "Libya"},
		{Model: gorm.Model{ID: 100}, Alpha2: "li", Alpha3: "lie", Name: "Liechtenstein"},
		{Model: gorm.Model{ID: 101}, Alpha2: "lt", Alpha3: "ltu", Name: "Lithuania"},
		{Model: gorm.Model{ID: 102}, Alpha2: "lu", Alpha3: "lux", Name: "Luxembourg"},
		{Model: gorm.Model{ID: 103}, Alpha2: "mg", Alpha3: "mdg", Name: "Madagascar"},
		{Model: gorm.Model{ID: 104}, Alpha2: "mw", Alpha3: "mwi", Name: "Malawi"},
		{Model: gorm.Model{ID: 105}, Alpha2: "my", Alpha3: "mys", Name: "Malaysia"},
		{Model: gorm.Model{ID: 106}, Alpha2: "mv", Alpha3: "mdv", Name: "Maldives"},
		{Model: gorm.Model{ID: 107}, Alpha2: "ml", Alpha3: "mli", Name: "Mali"},
		{Model: gorm.Model{ID: 108}, Alpha2: "mt", Alpha3: "mlt", Name: "Malta"},
		{Model: gorm.Model{ID: 109}, Alpha2: "mh", Alpha3: "mhl", Name: "Marshall Islands"},
		{Model: gorm.Model{ID: 110}, Alpha2: "mr", Alpha3: "mrt", Name: "Mauritania"},
		{Model: gorm.Model{ID: 111}, Alpha2: "mu", Alpha3: "mus", Name: "Mauritius"},
		{Model: gorm.Model{ID: 112}, Alpha2: "mx", Alpha3: "mex", Name: "Mexico"},
		{Model: gorm.Model{ID: 113}, Alpha2: "fm", Alpha3: "fsm", Name: "Micronesia (Federated States of)"},
		{Model: gorm.Model{ID: 114}, Alpha2: "md", Alpha3: "mda", Name: "Moldova, Republic of"},
		{Model: gorm.Model{ID: 115}, Alpha2: "mc", Alpha3: "mco", Name: "Monaco"},
		{Model: gorm.Model{ID: 116}, Alpha2: "mn", Alpha3: "mng", Name: "Mongolia"},
		{Model: gorm.Model{ID: 117}, Alpha2: "me", Alpha3: "mne", Name: "Montenegro"},
		{Model: gorm.Model{ID: 118}, Alpha2: "ma", Alpha3: "mar", Name: "Morocco"},
		{Model: gorm.Model{ID: 119}, Alpha2: "mz", Alpha3: "moz", Name: "Mozambique"},
		{Model: gorm.Model{ID: 120}, Alpha2: "mm", Alpha3: "mmr", Name: "Myanmar"},
		{Model: gorm.Model{ID: 121}, Alpha2: "na", Alpha3: "nam", Name: "Namibia"},
		{Model: gorm.Model{ID: 122}, Alpha2: "nr", Alpha3: "nru", Name: "Nauru"},
		{Model: gorm.Model{ID: 123}, Alpha2: "np", Alpha3: "npl", Name: "Nepal"},
		{Model: gorm.Model{ID: 124}, Alpha2: "nl", Alpha3: "nld", Name: "Netherlands"},
		{Model: gorm.Model{ID: 125}, Alpha2: "nz", Alpha3: "nzl", Name: "New Zealand"},
		{Model: gorm.Model{ID: 126}, Alpha2: "ni", Alpha3: "nic", Name: "Nicaragua"},
		{Model: gorm.Model{ID: 127}, Alpha2: "ne", Alpha3: "ner", Name: "Niger"},
		{Model: gorm.Model{ID: 128}, Alpha2: "ng", Alpha3: "nga", Name: "Nigeria"},
		{Model: gorm.Model{ID: 129}, Alpha2: "mk", Alpha3: "mkd", Name: "North Macedonia"},
		{Model: gorm.Model{ID: 130}, Alpha2: "no", Alpha3: "nor", Name: "Norway"},
		{Model: gorm.Model{ID: 131}, Alpha2: "om", Alpha3: "omn", Name: "Oman"},
		{Model: gorm.Model{ID: 132}, Alpha2: "pk", Alpha3: "pak", Name: "Pakistan"},
		{Model: gorm.Model{ID: 133}, Alpha2: "pw", Alpha3: "plw", Name: "Palau"},
		{Model: gorm.Model{ID: 134}, Alpha2: "pa", Alpha3: "pan", Name: "Panama"},
		{Model: gorm.Model{ID: 135}, Alpha2: "pg", Alpha3: "png", Name: "Papua New Guinea"},
		{Model: gorm.Model{ID: 136}, Alpha2: "py", Alpha3: "pry", Name: "Paraguay"},
		{Model: gorm.Model{ID: 137}, Alpha2: "pe", Alpha3: "per", Name: "Peru"},
		{Model: gorm.Model{ID: 138}, Alpha2: "ph", Alpha3: "phl", Name: "Philippines"},
		{Model: gorm.Model{ID: 139}, Alpha2: "pl", Alpha3: "pol", Name: "Poland"},
		{Model: gorm.Model{ID: 140}, Alpha2: "pt", Alpha3: "prt", Name: "Portugal"},
		{Model: gorm.Model{ID: 141}, Alpha2: "qa", Alpha3: "qat", Name: "Qatar"},
		{Model: gorm.Model{ID: 142}, Alpha2: "ro", Alpha3: "rou", Name: "Romania"},
		{Model: gorm.Model{ID: 143}, Alpha2: "ru", Alpha3: "rus", Name: "Russian Federation"},
		{Model: gorm.Model{ID: 144}, Alpha2: "rw", Alpha3: "rwa", Name: "Rwanda"},
		{Model: gorm.Model{ID: 145}, Alpha2: "kn", Alpha3: "kna", Name: "Saint Kitts and Nevis"},
		{Model: gorm.Model{ID: 146}, Alpha2: "lc", Alpha3: "lca", Name: "Saint Lucia"},
		{Model: gorm.Model{ID: 147}, Alpha2: "vc", Alpha3: "vct", Name: "Saint Vincent and the Grenadines"},
		{Model: gorm.Model{ID: 148}, Alpha2: "ws", Alpha3: "wsm", Name: "Samoa"},
		{Model: gorm.Model{ID: 149}, Alpha2: "sm", Alpha3: "smr", Name: "San Marino"},
		{Model: gorm.Model{ID: 150}, Alpha2: "st", Alpha3: "stp", Name: "Sao Tome and Principe"},
		{Model: gorm.Model{ID: 151}, Alpha2: "sa", Alpha3: "sau", Name: "Saudi Arabia"},
		{Model: gorm.Model{ID: 152}, Alpha2: "sn", Alpha3: "sen", Name: "Senegal"},
		{Model: gorm.Model{ID: 153}, Alpha2: "rs", Alpha3: "srb", Name: "Serbia"},
		{Model: gorm.Model{ID: 154}, Alpha2: "sc", Alpha3: "syc", Name: "Seychelles"},
		{Model: gorm.Model{ID: 155}, Alpha2: "sl", Alpha3: "sle", Name: "Sierra Leone"},
		{Model: gorm.Model{ID: 156}, Alpha2: "sg", Alpha3: "sgp", Name: "Singapore"},
		{Model: gorm.Model{ID: 157}, Alpha2: "sk", Alpha3: "svk", Name: "Slovakia"},
		{Model: gorm.Model{ID: 158}, Alpha2: "si", Alpha3: "svn", Name: "Slovenia"},
		{Model: gorm.Model{ID: 159}, Alpha2: "sb", Alpha3: "slb", Name: "Solomon Islands"},
		{Model: gorm.Model{ID: 160}, Alpha2: "so", Alpha3: "som", Name: "Somalia"},
		{Model: gorm.Model{ID: 161}, Alpha2: "za", Alpha3: "zaf", Name: "South Africa"},
		{Model: gorm.Model{ID: 162}, Alpha2: "ss", Alpha3: "ssd", Name: "South Sudan"},
		{Model: gorm.Model{ID: 163}, Alpha2: "es", Alpha3: "esp", Name: "Spain"},
		{Model: gorm.Model{ID: 164}, Alpha2: "lk", Alpha3: "lka", Name: "Sri Lanka"},
		{Model: gorm.Model{ID: 165}, Alpha2: "sd", Alpha3: "sdn", Name: "Sudan"},
		{Model: gorm.Model{ID: 166}, Alpha2: "sr", Alpha3: "sur", Name: "Suriname"},
		{Model: gorm.Model{ID: 167}, Alpha2: "se", Alpha3: "swe", Name: "Sweden"},
		{Model: gorm.Model{ID: 168}, Alpha2: "ch", Alpha3: "che", Name: "Switzerland"},
		{Model: gorm.Model{ID: 169}, Alpha2: "sy", Alpha3: "syr", Name: "Syrian Arab Republic"},
		{Model: gorm.Model{ID: 170}, Alpha2: "tj", Alpha3: "tjk", Name: "Tajikistan"},
		{Model: gorm.Model{ID: 171}, Alpha2: "tz", Alpha3: "tza", Name: "Tanzania, United Republic of"},
		{Model: gorm.Model{ID: 172}, Alpha2: "th", Alpha3: "tha", Name: "Thailand"},
		{Model: gorm.Model{ID: 173}, Alpha2: "tl", Alpha3: "tls", Name: "Timor-Leste"},
		{Model: gorm.Model{ID: 174}, Alpha2: "tg", Alpha3: "tgo", Name: "Togo"},
		{Model: gorm.Model{ID: 175}, Alpha2: "to", Alpha3: "ton", Name: "Tonga"},
		{Model: gorm.Model{ID: 176}, Alpha2: "tt", Alpha3: "tto", Name: "Trinidad and Tobago"},
		{Model: gorm.Model{ID: 177}, Alpha2: "tn", Alpha3: "tun", Name: "Tunisia"},
		{Model: gorm.Model{ID: 178}, Alpha2: "tr", Alpha3: "tur", Name: "TÃ¼rkiye"},
		{Model: gorm.Model{ID: 179}, Alpha2: "tm", Alpha3: "tkm", Name: "Turkmenistan"},
		{Model: gorm.Model{ID: 180}, Alpha2: "tv", Alpha3: "tuv", Name: "Tuvalu"},
		{Model: gorm.Model{ID: 181}, Alpha2: "ug", Alpha3: "uga", Name: "Uganda"},
		{Model: gorm.Model{ID: 182}, Alpha2: "ua", Alpha3: "ukr", Name: "Ukraine"},
		{Model: gorm.Model{ID: 183}, Alpha2: "ae", Alpha3: "are", Name: "United Arab Emirates"},
		{Model: gorm.Model{ID: 184}, Alpha2: "gb", Alpha3: "gbr", Name: "United Kingdom of Great Britain and Northern Ireland"},
		{Model: gorm.Model{ID: 185}, Alpha2: "us", Alpha3: "usa", Name: "United States of America"},
		{Model: gorm.Model{ID: 186}, Alpha2: "uy", Alpha3: "ury", Name: "Uruguay"},
		{Model: gorm.Model{ID: 187}, Alpha2: "uz", Alpha3: "uzb", Name: "Uzbekistan"},
		{Model: gorm.Model{ID: 188}, Alpha2: "vu", Alpha3: "vut", Name: "Vanuatu"},
		{Model: gorm.Model{ID: 189}, Alpha2: "ve", Alpha3: "ven", Name: "Venezuela (Bolivarian Republic of)"},
		{Model: gorm.Model{ID: 190}, Alpha2: "vn", Alpha3: "vnm", Name: "Viet Nam"},
		{Model: gorm.Model{ID: 191}, Alpha2: "ye", Alpha3: "yem", Name: "Yemen"},
		{Model: gorm.Model{ID: 192}, Alpha2: "zm", Alpha3: "zmb", Name: "Zambia"},
		{Model: gorm.Model{ID: 193}, Alpha2: "zw", Alpha3: "zwe", Name: "Zimbabwe"},
	}

	if int(count) == len(countries) {
		return
	}

	// Delete all records from the table
	deleteResult := initializers.DB.Session(&gorm.Session{AllowGlobalUpdate: true}).
		Unscoped().Delete(&models.Country{})
	if deleteResult.Error != nil {
		panic(deleteResult.Error)
	}

	// Use the Create method to insert records into the 'country' table
	if err := initializers.DB.Create(&countries).Error; err != nil {
		log.Fatal(err)
		panic(panicMessage)
	}

	fmt.Println("Country Table has been seeded successfully!")
}
